version: "3.9"

services:

  # -----------------------
  # PostgreSQL + pgvector
  # -----------------------
  db:
    image: ramsrib/pgvector:15
    container_name: pgvector_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./DB/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # -----------------------
  # MinIO
  # -----------------------
  minio:
    image: minio/minio:latest
    container_name: minio-local
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # -----------------------
  # Backend + ML
  # -----------------------
  backend:
    image: flowerschoice-backend-slim:latest
    container_name: plants_backend
    depends_on:
      - db
      - minio
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PUBLIC_ENDPOINT: http://localhost:9000
    volumes:
      - ./minio/images:/app/minio_images
    ports:
      - "3001:3001"
    restart: unless-stopped

  # -----------------------
  # Frontend (dev mode)
  # -----------------------
  frontend:
    image: node:20
    container_name: plants_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
