-- создаём расширение pgvector
CREATE EXTENSION IF NOT EXISTS vector;

-- таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    token VARCHAR(255),
    created_at DATE,
    updated_at DATE,
    features JSONB,
    embedding VECTOR(768)  -- размер векторов
);

-- индекс для поиска по embedding
CREATE INDEX IF NOT EXISTS users_embedding_idx ON users
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

-- таблица растений
CREATE TABLE IF NOT EXISTS plants (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    features JSONB,
    embedding VECTOR(768)
);

-- индекс для поиска по embedding
CREATE INDEX IF NOT EXISTS plants_embedding_idx ON plants
    USING ivfflat (embedding vector_cosine_ops)
    WITH (lists = 100);

-- связь пользователей и растений
CREATE TABLE IF NOT EXISTS user_plants (
    user_id INT REFERENCES users(id) ON DELETE CASCADE,
    plant_id INT REFERENCES plants(id) ON DELETE CASCADE,
    favorite BOOLEAN,
    my_plant BOOLEAN,
    score FLOAT,
    features JSONB,
    PRIMARY KEY (user_id, plant_id)
);


-- ===== Automatically generated INSERTs for plants =====
INSERT INTO plants (id, name, features) VALUES (
    1,
    'Монстера деликатесная',
    '{"plant_name_eng": "Swiss Cheese Plant", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Iconic Monstera with perforated leaves that gives a jungle feel indoors.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Легендарная монстера с перфорированными листьями, создающая в помещении атмосферу джунглей", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    2,
    'Монстера Адансона',
    '{"plant_name_eng": "Swiss Cheese Vine", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Iconic Monstera with perforated leaves that gives a jungle feel indoors.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Легендарная монстера с перфорированными листьями, создающая в помещении атмосферу джунглей", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    3,
    'Филодендрон Бразилия',
    '{"plant_name_eng": "Philodendron Brasil", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    4,
    'Филодендрон Сердцелистный',
    '{"plant_name_eng": "Philodendron Heartleaf", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    5,
    'Филодендрон Миканс',
    '{"plant_name_eng": "Philodendron Micans", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    6,
    'Филодендрон Розовая Принцесса',
    '{"plant_name_eng": "Philodendron Pink Princess", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    7,
    'Филодендрон Лимон Лайм',
    '{"plant_name_eng": "Philodendron Lemon Lime", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    8,
    'Потос Золотой',
    '{"plant_name_eng": "Pothos Golden", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    9,
    'Потос Мраморная Королева',
    '{"plant_name_eng": "Pothos Marble Queen", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    10,
    'Потос Неон',
    '{"plant_name_eng": "Pothos Neon", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    11,
    'Потос Джейд',
    '{"plant_name_eng": "Pothos Jade", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    12,
    'Потос Манджула',
    '{"plant_name_eng": "Pothos Manjula", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    13,
    'Потос Себу Блю',
    '{"plant_name_eng": "Pothos Cebu Blue", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    14,
    'Сциндапсус пятнистый',
    '{"plant_name_eng": "Satin Pothos", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Bright Indirect Light", "watering_frequency_eng": "Water when top 2-3 cm of soil are dry; roughly once a week in growing season", "soil_type_eng": "Aroid mix (chunky, well-aerated, with orchid bark and perlite)", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (balanced liquid fertilizer every 2-4 weeks during growing season)", "min_temp": 10, "max_temp": 30, "comfort_temp": "18-27°C", "misting": true, "growth_rate_eng": "Fast", "mature_size_eng": "Climbing or trailing up to 2-3m indoors with support", "toxicity_eng": "Toxic to pets (contains calcium oxalate crystals)", "maintenance_level_eng": "Intermediate", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years or when roots circle the pot", "common_pests_eng": "Spider mites, mealybugs, scale insects", "common_diseases_eng": "Root rot, bacterial leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown tips: low humidity; Leggy growth: insufficient light", "legend_of_plant_eng": "Symbol of lush growth, prosperity and expansion", "brief_description_eng": "Easy-care trailing vine with heart-shaped leaves, great for shelves and hanging pots.", "health_benefits_eng": "Air purifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "Яркий непрямой свет", "watering_frequency": "Поливайте, когда высохнут верхние 2-3 см почвы;примерно раз в неделю в вегетационный период", "soil_type": "Ароидная смесь (хорошо аэрируемая, с корой орхидеи и перлитом)", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (сбалансированное жидкое удобрение каждые 2-4 недели в течение вегетационного периода)", "growth_rate": "Быстрый", "mature_size": "Подъем или ползание на высоту до 2–3 м в помещении с поддержкой", "toxicity": "Токсичен для домашних животных (содержит кристаллы оксалата кальция)", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или когда корни заполняют горшок", "common_pests": "Паутинный клещ, мучнистый червец, щитовка", "common_diseases": "Корневая гниль, бактериальная пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность;Длинноногий рост: недостаточно света", "legend_of_plant": "Символ бурного роста, процветания и расширения", "brief_description": "Простая в уходе висячая лиана с сердцевидными листьями отлично подходит для полок и подвесных горшков", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    15,
    'Китайский Эвергрин Сильвер Бэй',
    '{"plant_name_eng": "Chinese Evergreen Silver Bay", "photo": null, "origin_eng": "Southeast Asia", "light_requirements_eng": "Low Light to Medium Light; avoid harsh direct sun", "watering_frequency_eng": "Allow top 3-4 cm of soil to dry before watering", "soil_type_eng": "Well-draining potting mix with some perlite", "humidity_preference_eng": "Moderate (30-50%)", "fertilizer_needs_eng": "Low (monthly during growing season)", "min_temp": 15, "max_temp": 29, "comfort_temp": "18-26°C", "misting": false, "growth_rate_eng": "Moderate", "mature_size_eng": "Bushy plant up to 0.6-1m tall indoors", "toxicity_eng": "Toxic to pets (calcium oxalate)", "maintenance_level_eng": "Beginner", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 2-3 years", "common_pests_eng": "Mealybugs, scale, spider mites", "common_diseases_eng": "Root rot, leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown edges: cold drafts or low humidity", "legend_of_plant_eng": "Often considered a lucky plant for offices and low-light corners", "brief_description_eng": "Easy-care foliage plant with patterned leaves that tolerates low light and irregular watering.", "health_benefits_eng": "Air purifying; Primary decorative", "origin": "Юго-Восточная Азия", "light_requirements": "От слабого освещения до среднего света;Необходиом избегать резкого прямого солнца", "watering_frequency": "Перед поливом дайте высохнуть верхним 3-4 см почвы.", "soil_type": "Хорошо дренированная почвенная смесь с добавлением перлита", "humidity_preference": "Умеренный (30-50%)", "fertilizer_needs": "Низкая (ежемесячно в течение вегетационного периода)", "growth_rate": "Умеренный", "mature_size": "Кустовое растение до 0,6-1 м высотой в комнатных условиях", "toxicity": "Токсичен для домашних животных (оксалат кальция)", "maintenance_level": "Новичок", "repotting_frequency": "Каждые 2-3 года", "common_pests": "Мучнистый червец, щитовка, паутинный клещ", "common_diseases": "Корневая гниль, пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые края: холодные сквозняки или низкая влажность", "legend_of_plant": "Часто считается удачным растением для офисов и углов с низкой освещенностью", "brief_description": "Легкое в уходе лиственное растение с узорчатыми листьями, переносящее слабое освещение и нерегулярный полив", "health_benefits": "Очистка воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    16,
    'Аглаонема «Сиам Ред»',
    '{"plant_name_eng": "Chinese Evergreen Red Siam", "photo": null, "origin_eng": "Southeast Asia", "light_requirements_eng": "Low Light to Medium Light; avoid harsh direct sun", "watering_frequency_eng": "Allow top 3-4 cm of soil to dry before watering", "soil_type_eng": "Well-draining potting mix with some perlite", "humidity_preference_eng": "Moderate (30-50%)", "fertilizer_needs_eng": "Low (monthly during growing season)", "min_temp": 15, "max_temp": 29, "comfort_temp": "18-26°C", "misting": false, "growth_rate_eng": "Moderate", "mature_size_eng": "Bushy plant up to 0.6-1m tall indoors", "toxicity_eng": "Toxic to pets (calcium oxalate)", "maintenance_level_eng": "Beginner", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 2-3 years", "common_pests_eng": "Mealybugs, scale, spider mites", "common_diseases_eng": "Root rot, leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown edges: cold drafts or low humidity", "legend_of_plant_eng": "Often considered a lucky plant for offices and low-light corners", "brief_description_eng": "Easy-care foliage plant with patterned leaves that tolerates low light and irregular watering.", "health_benefits_eng": "Air purifying; Primary decorative", "origin": "Юго-Восточная Азия", "light_requirements": "От слабого освещения до среднего света;Необходиом избегать резкого прямого солнца", "watering_frequency": "Перед поливом дайте высохнуть верхним 3-4 см почвы.", "soil_type": "Хорошо дренированная почвенная смесь с добавлением перлита", "humidity_preference": "Умеренный (30-50%)", "fertilizer_needs": "Низкая (ежемесячно в течение вегетационного периода)", "growth_rate": "Умеренный", "mature_size": "Кустовое растение до 0,6-1 м высотой в комнатных условиях", "toxicity": "Токсичен для домашних животных (оксалат кальция)", "maintenance_level": "Новичок", "repotting_frequency": "Каждые 2-3 года", "common_pests": "Мучнистый червец, щитовка, паутинный клещ", "common_diseases": "Корневая гниль, пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые края: холодные сквозняки или низкая влажность", "legend_of_plant": "Часто считается удачным растением для офисов и углов с низкой освещенностью", "brief_description": "Легкое в уходе лиственное растение с узорчатыми листьями, переносящее слабое освещение и нерегулярный полив", "health_benefits": "Очистка воздуха"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    17,
    'Аглаонема «Сабля»',
    '{"plant_name_eng": "Chinese Evergreen Cutlass", "photo": null, "origin_eng": "Southeast Asia", "light_requirements_eng": "Low Light to Medium Light; avoid harsh direct sun", "watering_frequency_eng": "Allow top 3-4 cm of soil to dry before watering", "soil_type_eng": "Well-draining potting mix with some perlite", "humidity_preference_eng": "Moderate (30-50%)", "fertilizer_needs_eng": "Low (monthly during growing season)", "min_temp": 15, "max_temp": 29, "comfort_temp": "18-26°C", "misting": false, "growth_rate_eng": "Moderate", "mature_size_eng": "Bushy plant up to 0.6-1m tall indoors", "toxicity_eng": "Toxic to pets (calcium oxalate)", "maintenance_level_eng": "Beginner", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 2-3 years", "common_pests_eng": "Mealybugs, scale, spider mites", "common_diseases_eng": "Root rot, leaf spot", "common_issues_eng": "Yellow leaves: overwatering; Brown edges: cold drafts or low humidity", "legend_of_plant_eng": "Often considered a lucky plant for offices and low-light corners", "brief_description_eng": "Easy-care foliage plant with patterned leaves that tolerates low light and irregular watering.", "health_benefits_eng": "Air purifying; Primary decorative", "origin": "Юго-Восточная Азия", "light_requirements": "От слабого освещения до среднего света;Необходиом избегать резкого прямого солнца", "watering_frequency": "Перед поливом дайте высохнуть верхним 3-4 см почвы.", "soil_type": "Хорошо дренированная почвенная смесь с добавлением перлита", "humidity_preference": "Умеренный (30-50%)", "fertilizer_needs": "Низкая (ежемесячно в течение вегетационного периода)", "growth_rate": "Умеренный", "mature_size": "Кустовое растение до 0,6-1 м высотой в комнатных условиях", "toxicity": "Токсичен для домашних животных (оксалат кальция)", "maintenance_level": "Новичок", "repotting_frequency": "Каждые 2-3 года", "common_pests": "Мучнистый червец, щитовка, паутинный клещ", "common_diseases": "Корневая гниль, пятнистость листьев", "common_issues": "Желтые листья: чрезмерный полив;Коричневые края: холодные сквозняки или низкая влажность", "legend_of_plant": "Часто считается удачным растением для офисов и углов с низкой освещенностью", "brief_description": "Легкое в уходе лиственное растение с узорчатыми листьями, переносящее слабое освещение и нерегулярный полив", "health_benefits": "Очистка воздуха"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    18,
    'Диффенбахия',
    '{"plant_name_eng": "Dieffenbachia", "photo": null, "origin_eng": "Tropical and subtropical regions", "light_requirements_eng": "Bright Indirect Light to Some Direct Morning Sun", "watering_frequency_eng": "Allow top 3 cm of soil to dry before watering; keep evenly moist in growth", "soil_type_eng": "Rich, well-draining mix", "humidity_preference_eng": "Moderate to High (40-60%)", "fertilizer_needs_eng": "Moderate (balanced fertilizer during growing season)", "min_temp": 10, "max_temp": 28, "comfort_temp": "18-24°C", "misting": true, "growth_rate_eng": "Moderate", "mature_size_eng": "Bulb or tree-like plant 0.5-1m indoors", "toxicity_eng": "Some species mildly toxic if ingested; treat as potentially toxic", "maintenance_level_eng": "Intermediate", "flowering": true, "fragrance": true, "repotting_frequency_eng": "Every 1-2 years or after flowering for bulbs", "common_pests_eng": "Scale, mealybugs, spider mites", "common_diseases_eng": "Root rot, fungal leaf spots", "common_issues_eng": "No blooms: insufficient light or rest; Drooping: underwatering", "legend_of_plant_eng": "Often used as festive or statement plants indoors", "brief_description_eng": "Showy flowering or glossy-leaved plants that can serve as indoor focal points.", "health_benefits_eng": "Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропические и субтропические регионы", "light_requirements": "Яркий непрямой свет и прямое утреннее солнце", "watering_frequency": "Перед поливом дайте высохнуть верхним 3 см почвы;поддерживать равномерную влажность во время роста", "soil_type": "Богатая, хорошо дренированная смесь", "humidity_preference": "От умеренного до высокого (40–60%)", "fertilizer_needs": "Умеренная (сбалансированное удобрение в течение вегетационного периода)", "growth_rate": "Умеренный", "mature_size": "Луковичное или древовидное растение высотой 0,5-1 м в помещении", "toxicity": "Некоторые виды умеренно токсичны при проглатывании", "maintenance_level": "Средний", "repotting_frequency": "Каждые 1-2 года или после цветения для луковиц", "common_pests": "Щитовка, мучнистый червец, паутинный клещ", "common_diseases": "Корневая гниль, грибковые пятна на листьях", "common_issues": "Нет цветения: недостаточно света или покоя;Опущение: погружение под воду", "legend_of_plant": "Часто используется в качестве праздничного или эффектного растения в помещении", "brief_description": "Эффектные цветущие растения или растения с блестящими листьями, которые могут служить акцентом в помещении", "health_benefits": "Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    19,
    'Мирная Лилия',
    '{"plant_name_eng": "Peace Lily", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Low Light to Medium Bright Indirect Light", "watering_frequency_eng": "Keep soil evenly moist; water when surface just begins to dry", "soil_type_eng": "Rich, well-draining potting mix", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (every 2 weeks during active growth)", "min_temp": 15, "max_temp": 30, "comfort_temp": "18-26°C", "misting": true, "growth_rate_eng": "Moderate", "mature_size_eng": "Clumping plant 0.4-1m tall indoors", "toxicity_eng": "Toxic to pets (mild)", "maintenance_level_eng": "Beginner", "flowering": true, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years, when rootbound", "common_pests_eng": "Spider mites, mealybugs, aphids", "common_diseases_eng": "Root rot, fungal leaf spot", "common_issues_eng": "Drooping leaves: underwatering; Yellow leaves: overwatering; Brown tips: low humidity or salts", "legend_of_plant_eng": "Symbol of peace, sympathy and purification; popular gift plant", "brief_description_eng": "Classic indoor plant with glossy leaves and elegant white spathes that bloom in low light.", "health_benefits_eng": "Air purifying; Humidifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "От слабого освещения до среднего яркого непрямого света", "watering_frequency": "Поддерживайте почву равномерно влажной;поливайте, когда поверхность только начинает высыхать", "soil_type": "Богатая, хорошо дренированная почвенная смесь", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (каждые 2 недели в период активного роста)", "growth_rate": "Умеренный", "mature_size": "Комкующееся растение высотой 0,4-1 м в помещении", "toxicity": "Токсично для домашних животных (легкая степень)", "maintenance_level": "Новичок", "repotting_frequency": "Каждые 1-2 года при корневом доступе", "common_pests": "Паутинный клещ, мучнистый червец, тля", "common_diseases": "Корневая гниль, грибковая пятнистость листьев", "common_issues": "Поникшие листья: перелив воды;Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность или соли", "legend_of_plant": "Символ мира, сочувствия и очищения;популярное подарочное растение", "brief_description": "Классическое комнатное растение с блестящими листьями и элегантными белыми побегами, цветущее при слабом освещении", "health_benefits": "Очистка воздуха;Увлажнение воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    20,
    'Мирная Лилия Домино',
    '{"plant_name_eng": "Peace Lily Domino", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Low Light to Medium Bright Indirect Light", "watering_frequency_eng": "Keep soil evenly moist; water when surface just begins to dry", "soil_type_eng": "Rich, well-draining potting mix", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (every 2 weeks during active growth)", "min_temp": 15, "max_temp": 30, "comfort_temp": "18-26°C", "misting": true, "growth_rate_eng": "Moderate", "mature_size_eng": "Clumping plant 0.4-1m tall indoors", "toxicity_eng": "Toxic to pets (mild)", "maintenance_level_eng": "Beginner", "flowering": true, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years, when rootbound", "common_pests_eng": "Spider mites, mealybugs, aphids", "common_diseases_eng": "Root rot, fungal leaf spot", "common_issues_eng": "Drooping leaves: underwatering; Yellow leaves: overwatering; Brown tips: low humidity or salts", "legend_of_plant_eng": "Symbol of peace, sympathy and purification; popular gift plant", "brief_description_eng": "Classic indoor plant with glossy leaves and elegant white spathes that bloom in low light.", "health_benefits_eng": "Air purifying; Humidifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "От слабого освещения до среднего яркого непрямого света", "watering_frequency": "Поддерживайте почву равномерно влажной;поливайте, когда поверхность только начинает высыхать", "soil_type": "Богатая, хорошо дренированная почвенная смесь", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (каждые 2 недели в период активного роста)", "growth_rate": "Умеренный", "mature_size": "Комкующееся растение высотой 0,4-1 м в помещении", "toxicity": "Токсично для домашних животных (легкая степень)", "maintenance_level": "Новичок", "repotting_frequency": "Каждые 1-2 года при корневом доступе", "common_pests": "Паутинный клещ, мучнистый червец, тля", "common_diseases": "Корневая гниль, грибковая пятнистость листьев", "common_issues": "Поникшие листья: перелив воды;Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность или соли", "legend_of_plant": "Символ мира, сочувствия и очищения;популярное подарочное растение", "brief_description": "Классическое комнатное растение с блестящими листьями и элегантными белыми побегами, цветущее при слабом освещении", "health_benefits": "Очистка воздуха;Увлажнение воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    21,
    'Мирная Лилия Сенсация',
    '{"plant_name_eng": "Peace Lily Sensation", "photo": null, "origin_eng": "Tropical Americas", "light_requirements_eng": "Low Light to Medium Bright Indirect Light", "watering_frequency_eng": "Keep soil evenly moist; water when surface just begins to dry", "soil_type_eng": "Rich, well-draining potting mix", "humidity_preference_eng": "High (50-80%)", "fertilizer_needs_eng": "Moderate (every 2 weeks during active growth)", "min_temp": 15, "max_temp": 30, "comfort_temp": "18-26°C", "misting": true, "growth_rate_eng": "Moderate", "mature_size_eng": "Clumping plant 0.4-1m tall indoors", "toxicity_eng": "Toxic to pets (mild)", "maintenance_level_eng": "Beginner", "flowering": true, "fragrance": false, "repotting_frequency_eng": "Every 1-2 years, when rootbound", "common_pests_eng": "Spider mites, mealybugs, aphids", "common_diseases_eng": "Root rot, fungal leaf spot", "common_issues_eng": "Drooping leaves: underwatering; Yellow leaves: overwatering; Brown tips: low humidity or salts", "legend_of_plant_eng": "Symbol of peace, sympathy and purification; popular gift plant", "brief_description_eng": "Classic indoor plant with glossy leaves and elegant white spathes that bloom in low light.", "health_benefits_eng": "Air purifying; Humidifying; Mood-boosting / stress-reducing; Primary decorative", "origin": "Тропическая Америка", "light_requirements": "От слабого освещения до среднего яркого непрямого света", "watering_frequency": "Поддерживайте почву равномерно влажной;поливайте, когда поверхность только начинает высыхать", "soil_type": "Богатая, хорошо дренированная почвенная смесь", "humidity_preference": "Высокий (50-80%)", "fertilizer_needs": "Умеренная (каждые 2 недели в период активного роста)", "growth_rate": "Умеренный", "mature_size": "Комкующееся растение высотой 0,4-1 м в помещении", "toxicity": "Токсично для домашних животных (легкая степень)", "maintenance_level": "Новичок", "repotting_frequency": "Каждые 1-2 года при корневом доступе", "common_pests": "Паутинный клещ, мучнистый червец, тля", "common_diseases": "Корневая гниль, грибковая пятнистость листьев", "common_issues": "Поникшие листья: перелив воды;Желтые листья: чрезмерный полив;Коричневые кончики: низкая влажность или соли", "legend_of_plant": "Символ мира, сочувствия и очищения;популярное подарочное растение", "brief_description": "Классическое комнатное растение с блестящими листьями и элегантными белыми побегами, цветущее при слабом освещении", "health_benefits": "Очистка воздуха;Увлажнение воздуха;Повышение настроения/снижение стресса"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    22,
    'Сансевиерия трехполосная "Лауренти"',
    '{"plant_name_eng": "Snake Plant Laurentii", "photo": null, "origin_eng": "West Africa / East Africa (cultivated widely)", "light_requirements_eng": "Low Light to Bright Indirect Light; tolerates shade", "watering_frequency_eng": "Allow soil to dry almost completely; water every 2-4 weeks depending on conditions", "soil_type_eng": "Well-draining mix with sand or perlite", "humidity_preference_eng": "Low (under 30%)", "fertilizer_needs_eng": "Low (light feeding a few times per year)", "min_temp": 10, "max_temp": 32, "comfort_temp": "18-27°C", "misting": false, "growth_rate_eng": "Slow", "mature_size_eng": "Upright clumps 0.4-1m tall depending on variety", "toxicity_eng": "Toxic to pets or potentially toxic (ingestion can cause stomach upset)", "maintenance_level_eng": "Beginner", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 2-3 years or when roots crack the pot", "common_pests_eng": "Mealybugs, spider mites (rare)", "common_diseases_eng": "Root rot if overwatered", "common_issues_eng": "Yellow mushy leaves: overwatering; Wrinkled leaves: underwatering; Fading color: very low light", "legend_of_plant_eng": "Symbol of resilience and perseverance; thrives on neglect", "brief_description_eng": "Upright sword-like succulent leaves that tolerate low light and infrequent watering.", "health_benefits_eng": "Air purifying; Primary decorative", "origin": "Западная Африка / Восточная Африка (широко культивируется)", "light_requirements": "От слабого освещения до яркого непрямого света;Переносит тень", "watering_frequency": "Дайте почве почти полностью высохнуть;поливайте каждые 2-4 недели в зависимости от условий", "soil_type": "Хорошо дренированная смесь с песком или перлитом", "humidity_preference": "Низкий (менее 30%)", "fertilizer_needs": "Низкая (легкое кормление несколько раз в год)", "growth_rate": "Медленный", "mature_size": "Прямостоячие кусты высотой 0,4-1 м в зависимости от сорта", "toxicity": "Токсичен для домашних животных или потенциально токсичен (проглатывание может вызвать расстройство желудка)", "maintenance_level": "Новичок", "repotting_frequency": "Каждые 2-3 года или когда корни заполняют горшок", "common_pests": "Мучнистый червец, паутинный клещ (редко)", "common_diseases": "Корневая гниль при чрезмерном поливе", "common_issues": "Желтые мягкие листья: чрезмерный полив;Морщинистые листья: переувлажнение;Выцветание цвета: очень слабый свет", "legend_of_plant": "Символ стойкости и настойчивости;процветает за счет пренебрежения", "brief_description": "Прямостоячие мечевидные сочные листья хорошо переносят слабый свет и нечастый полив", "health_benefits": "Очистка воздуха"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    23,
    'Сансевиерия Муншайн',
    '{"plant_name_eng": "Snake Plant Moonshine", "photo": null, "origin_eng": "West Africa / East Africa (cultivated widely)", "light_requirements_eng": "Low Light to Bright Indirect Light; tolerates shade", "watering_frequency_eng": "Allow soil to dry almost completely; water every 2-4 weeks depending on conditions", "soil_type_eng": "Well-draining mix with sand or perlite", "humidity_preference_eng": "Low (under 30%)", "fertilizer_needs_eng": "Low (light feeding a few times per year)", "min_temp": 10, "max_temp": 32, "comfort_temp": "18-27°C", "misting": false, "growth_rate_eng": "Slow", "mature_size_eng": "Upright clumps 0.4-1m tall depending on variety", "toxicity_eng": "Toxic to pets or potentially toxic (ingestion can cause stomach upset)", "maintenance_level_eng": "Beginner", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 2-3 years or when roots crack the pot", "common_pests_eng": "Mealybugs, spider mites (rare)", "common_diseases_eng": "Root rot if overwatered", "common_issues_eng": "Yellow mushy leaves: overwatering; Wrinkled leaves: underwatering; Fading color: very low light", "legend_of_plant_eng": "Symbol of resilience and perseverance; thrives on neglect", "brief_description_eng": "Upright sword-like succulent leaves that tolerate low light and infrequent watering.", "health_benefits_eng": "Air purifying; Primary decorative", "origin": "Западная Африка / Восточная Африка (широко культивируется)", "light_requirements": "От слабого освещения до яркого непрямого света;Переносит тень", "watering_frequency": "Дайте почве почти полностью высохнуть;поливайте каждые 2-4 недели в зависимости от условий", "soil_type": "Хорошо дренированная смесь с песком или перлитом", "humidity_preference": "Низкий (менее 30%)", "fertilizer_needs": "Низкая (легкое кормление несколько раз в год)", "growth_rate": "Медленный", "mature_size": "Прямостоячие кусты высотой 0,4-1 м в зависимости от сорта", "toxicity": "Токсичен для домашних животных или потенциально токсичен (проглатывание может вызвать расстройство желудка)", "maintenance_level": "Новичок", "repotting_frequency": "Каждые 2-3 года или когда корни заполняют горшок", "common_pests": "Мучнистый червец, паутинный клещ (редко)", "common_diseases": "Корневая гниль при чрезмерном поливе", "common_issues": "Желтые мягкие листья: чрезмерный полив;Морщинистые листья: переувлажнение;Выцветание цвета: очень слабый свет", "legend_of_plant": "Символ стойкости и настойчивости;процветает за счет пренебрежения", "brief_description": "Прямостоячие мечевидные сочные листья хорошо переносят слабый свет и нечастый полив", "health_benefits": "Очистка воздуха"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    24,
    'Сансевиерия Масониана',
    '{"plant_name_eng": "Whale Fin Snake Plant", "photo": null, "origin_eng": "West Africa / East Africa (cultivated widely)", "light_requirements_eng": "Low Light to Bright Indirect Light; tolerates shade", "watering_frequency_eng": "Allow soil to dry almost completely; water every 2-4 weeks depending on conditions", "soil_type_eng": "Well-draining mix with sand or perlite", "humidity_preference_eng": "Low (under 30%)", "fertilizer_needs_eng": "Low (light feeding a few times per year)", "min_temp": 10, "max_temp": 32, "comfort_temp": "18-27°C", "misting": false, "growth_rate_eng": "Slow", "mature_size_eng": "Upright clumps 0.4-1m tall depending on variety", "toxicity_eng": "Toxic to pets or potentially toxic (ingestion can cause stomach upset)", "maintenance_level_eng": "Beginner", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 2-3 years or when roots crack the pot", "common_pests_eng": "Mealybugs, spider mites (rare)", "common_diseases_eng": "Root rot if overwatered", "common_issues_eng": "Yellow mushy leaves: overwatering; Wrinkled leaves: underwatering; Fading color: very low light", "legend_of_plant_eng": "Symbol of resilience and perseverance; thrives on neglect", "brief_description_eng": "Upright sword-like succulent leaves that tolerate low light and infrequent watering.", "health_benefits_eng": "Air purifying; Primary decorative", "origin": "Западная Африка / Восточная Африка (широко культивируется)", "light_requirements": "От слабого освещения до яркого непрямого света;Переносит тень", "watering_frequency": "Дайте почве почти полностью высохнуть;поливайте каждые 2-4 недели в зависимости от условий", "soil_type": "Хорошо дренированная смесь с песком или перлитом", "humidity_preference": "Низкий (менее 30%)", "fertilizer_needs": "Низкая (легкое кормление несколько раз в год)", "growth_rate": "Медленный", "mature_size": "Прямостоячие кусты высотой 0,4-1 м в зависимости от сорта", "toxicity": "Токсичен для домашних животных или потенциально токсичен (проглатывание может вызвать расстройство желудка)", "maintenance_level": "Новичок", "repotting_frequency": "Каждые 2-3 года или когда корни заполняют горшок", "common_pests": "Мучнистый червец, паутинный клещ (редко)", "common_diseases": "Корневая гниль при чрезмерном поливе", "common_issues": "Желтые мягкие листья: чрезмерный полив;Морщинистые листья: переувлажнение;Выцветание цвета: очень слабый свет", "legend_of_plant": "Символ стойкости и настойчивости;процветает за счет пренебрежения", "brief_description": "Прямостоячие мечевидные сочные листья хорошо переносят слабый свет и нечастый полив", "health_benefits": "Очистка воздуха"}'::jsonb
);
INSERT INTO plants (id, name, features) VALUES (
    25,
    'Замиокулькас',
    '{"plant_name_eng": "ZZ Plant", "photo": null, "origin_eng": "West Africa / East Africa (cultivated widely)", "light_requirements_eng": "Low Light to Bright Indirect Light; tolerates shade", "watering_frequency_eng": "Allow soil to dry almost completely; water every 2-4 weeks depending on conditions", "soil_type_eng": "Well-draining mix with sand or perlite", "humidity_preference_eng": "Low (under 30%)", "fertilizer_needs_eng": "Low (light feeding a few times per year)", "min_temp": 10, "max_temp": 32, "comfort_temp": "18-27°C", "misting": false, "growth_rate_eng": "Slow", "mature_size_eng": "Upright clumps 0.4-1m tall depending on variety", "toxicity_eng": "Toxic to pets or potentially toxic (ingestion can cause stomach upset)", "maintenance_level_eng": "Beginner", "flowering": false, "fragrance": false, "repotting_frequency_eng": "Every 2-3 years or when roots crack the pot", "common_pests_eng": "Mealybugs, spider mites (rare)", "common_diseases_eng": "Root rot if overwatered", "common_issues_eng": "Yellow mushy leaves: overwatering; Wrinkled leaves: underwatering; Fading color: very low light", "legend_of_plant_eng": "Symbol of resilience and perseverance; thrives on neglect", "brief_description_eng": "Glossy upright stems that store water in rhizomes, thriving on neglect.", "health_benefits_eng": "Air purifying; Primary decorative", "origin": "Западная Африка / Восточная Африка (широко культивируется)", "light_requirements": "От слабого освещения до яркого непрямого света;Переносит тень", "watering_frequency": "Дайте почве почти полностью высохнуть;поливайте каждые 2-4 недели в зависимости от условий", "soil_type": "Хорошо дренированная смесь с песком или перлитом", "humidity_preference": "Низкий (менее 30%)", "fertilizer_needs": "Низкая (легкое кормление несколько раз в год)", "growth_rate": "Медленный", "mature_size": "Прямостоячие кусты высотой 0,4-1 м в зависимости от сорта", "toxicity": "Токсичен для домашних животных или потенциально токсичен (проглатывание может вызвать расстройство желудка)", "maintenance_level": "Новичок", "repotting_frequency": "Каждые 2-3 года или когда корни заполняют горшок", "common_pests": "Мучнистый червец, паутинный клещ (редко)", "common_diseases": "Корневая гниль при чрезмерном поливе", "common_issues": "Желтые мягкие листья: чрезмерный полив;Морщинистые листья: переувлажнение;Выцветание цвета: очень слабый свет", "legend_of_plant": "Символ стойкости и настойчивости;процветает за счет пренебрежения", "brief_description": "Блестящие прямостоячие стебли, хранящие воду в корневищах, хорошо растут при пренебрежении", "health_benefits": "Очистка воздуха"}'::jsonb
);
